### ISSUE TITLE
MNT: Remove TEAL

### ISSUE THREAD

**Issue by pllim** [spacetelescope/acstools#106]
If TEAL interface is not used here, we can safely remove it. @tddesjardins will discuss with @nagrogin

**Comment by nmiles2718** [comment]
After discussion with @tddesjardins and @nagrogin, we are all in favor of removing TEAL support in `acstools`. The reasoning here is that there are no modules within `acstools` that are actually complicated enough to benefit from the TEAL GUI. Hence, the effort required to support the TEAL interface for `acstools` outweighs the benefits of having it and so it doesn't make sense from an FTE standpoint to continue supporting it when there is other work to be done.
