### ISSUE TITLE
Will acs_destripe_plus automatically use CTE gen 2 correction?

### ISSUE THREAD

**Issue by pllim** [spacetelescope/acstools#24]
This question was asked by ACS Team during team meeting today. I told them, "yes" but would be nice to have direct confirmation from @jamienoss .

Any changes needed to make this work will need to be coordinated with HSTDP 2017.2a delivery.

c/c @stsci-hack

**Comment by jamienoss** [comment]
It should be completely transparent but I will run some tests later today.

**Comment by jamienoss** [comment]
It works. I'll have to find a subarray image, however, to extend the test.

**Comment by jamienoss** [comment]
It works on the 'new' subarray images once [hstcal:#155](https://github.com/spacetelescope/hstcal/issues/155) has been resolved.
