### ISSUE TITLE
Update CALACS doc to include new Gen 2 options

### ISSUE THREAD

**Issue by pllim** [spacetelescope/acstools#25]
This needs to be updated:
http://acstools.readthedocs.io/en/latest/calacs_hstcal.html

Source is here:
https://github.com/spacetelescope/acstools/blob/master/doc/source/calacs_hstcal.rst

Also, did this change?
http://acstools.readthedocs.io/en/latest/calacs.html

**Comment by jamienoss** [comment]
None of the command line options were propagated through to ``ACSTOOLS`` so http://acstools.readthedocs.io/en/latest/calacs.html does not need to be changed.

**Comment by jamienoss** [comment]
Thanks for pointing this out BTW :)

**Comment by jamienoss** [comment]
How or when etc is http://acstools.readthedocs.io/en/latest/calacs_hstcal.html built/updated? is this done manually or...?

**Comment by jamienoss** [comment]
Is there an ISR for the new CTE correction? (I'll email Norman)

**Comment by pllim** [comment]
ReadTheDocs builds the doc whenever you commit to `master`.

**Comment by jamienoss** [comment]
The docs shouldn't be built and updated from master. They should be building the last release only, right?

**Comment by pllim** [comment]
ReadTheDocs builds from `master` and release tags. The link you point out is "latest", thus points to `master`. If you replace "latest" with "stable", it should point to latest release.

**Comment by jamienoss** [comment]
Awesome, thanks.
