### ISSUE TITLE
Fix satdet regression test failure in dev and public

### ISSUE THREAD

**Issue by pllim** [spacetelescope/acstools#28]
Satellite detection trail regression test in ACSTOOLS started failing on June 14, 2017. At first, I thought it was due to astropy/astropy#6207 but that was not merged into Astropy dev until June 15. Both code and test data have not been recently changed, so it is likely that some behavior change upstream (scipy?) caused this.

https://ssb.stsci.edu/pandokia/pandokia.cgi?query=detail&key_id=102860998

Note: Affects both test machines on dev.

c/c @dborncamp 

GIF courtesy of Dave Borncamp blinking between bad output and good "truth":
![satdetfail](https://user-images.githubusercontent.com/2090236/28091398-9c9374cc-665d-11e7-819e-35dc86af998b.gif)

**Comment by dborncamp** [comment]
I see the test failing in the pandokia engine but can I get at the data somehow?

**Comment by dborncamp** [comment]
I cannot reproduce this error. Could you give me more information on the environment?

**Comment by pllim** [comment]
@jhunkeler or @rendinam know where to dig that out.

**Comment by pllim** [comment]
@dborncamp , by the way, in the test log given above, don't worry about the traceback at the end, but rather note that `fitsdiff` reported differences in result, which I think is also what you see?

**Comment by pllim** [comment]
Update: Dave Borncamp was unable to produce the bad output on his environment but I am able to... My bet is on some changes upstream between Astropy 1.3 and 2.0. Maybe astropy/astropy#5991 but why it did not show up until June 14 on dev (which is supposed to pick up Astropy dev), I don't know.

**Comment by pllim** [comment]
There is still some differences but they appear to me as aliasing effect: https://ssb.stsci.edu/pandokia/pandokia.cgi?query=detail&key_id=105008197

@dborncamp, those files are temporarily at `/eng/ssb/lim/acstools_issue29`. Please have a look and see if the differences are acceptable. Thanks!

**Comment by dborncamp** [comment]
These changes are good. Thanks @pllim!
