### ISSUE TITLE
Bi-quadratic interpolation in skimage changed due to bug. Is there a reason why the rotation order in make_mask (line 811) is set to 2 instead of order? Since the bi-quadratic code has changed, I find running make_mask takes a very long time and often fails due to the order setting.

### ISSUE THREAD

**Issue by KerryPaterson** [spacetelescope/acstools#3]

**Comment by pllim** [comment]
@KerryPaterson , please send your question to `help[at]stsci.edu` so it can be routed to the appropriate person in the ACS Team who wrote the original algorithm. We currently do not take help calls via GitHub. Thank you.

**Comment by pllim** [comment]
@KerryPaterson , please see if the fix in [v2.0.1](https://github.com/spacetelescope/acstools/releases/tag/2.0.1) works for you. Thank you for reporting this!
