### ISSUE TITLE
calacs in notebooks messes up logging

### ISSUE THREAD

**Issue by tddesjardins** [spacetelescope/acstools#54]
When running `calacs` as part of a jupyter notebook, subsequent tasks that use the `logging` module (e.g., `astrodrizzle`) start printing all logging messages to the STDOUT as well as to the logfile they create in addition to the normal messages they print to STDOUT. This has the effect of duplicating much of the information these programs normally print. I've attached an example screenshot. 

![screen shot 2018-04-17 at 4 20 06 pm](https://user-images.githubusercontent.com/20800912/39007843-f7751454-43d4-11e8-8b92-4f55d7ed3bf5.png)

Through testing of individual cells in the notebook, I've narrowed down that it's the cell that imports and runs `calacs` that is causing this behavior. The cell contains only:

```
from acstools import calacs

calacs.calacs('j9l960010_asn.fits')
```

If I save the FLT files `calacs` produces, restart the kernel in the notebook and clear all outputs, and skip the cell that imports and runs `calacs`, then I don't get this behavior with the `logging` messages and only things that are normally printed to STDOUT appear in the output cell.

**Comment by jamienoss** [comment]
* Has this only _just_ started happening?

**Comment by jamienoss** [comment]
I also don't understand the interplay, here, between the diff cells.

Your screenshot above is from tweakreg and shows some degree of duplicated messaging, but if calacs is being executed from a diff cell then how does it have anything to do with the tweakreg cell and its duplicated messages?

**Comment by pllim** [comment]
As far as I can see, `calacs.py` wrapper simply calls `subprocess.check_call()`. @tddesjardins , does this behavior persist if you run `calacs.e` in your notebook *without* the wrapper, for example:
```
!calacs.e blahblahblah
```
?

**Comment by pllim** [comment]
A workaround for now is to manually set logging level in `drizzlepac` to WARNING or ERROR (see https://docs.python.org/3/library/logging.html#levels). @mcara , how does one control logging behavior in `drizzlepac`?

**Comment by mcara** [comment]
@pllim From what I see one cannot control anything about logging in astrodrizzle (well, except for file name). Level of warning is hardcoded like `log.info()`, `log.warn()`, etc.

**Comment by pllim** [comment]
@mcara, is there no way do use `log.setLevel()`?

**Comment by mcara** [comment]
Maybe you can try doing something like:
```
from drizzlepac import astrodrizzle
astrodrizzle.log.setLevel(logging.ERROR)
```

**Comment by mcara** [comment]
@pllim I tried this and it seems to have no effect. Maybe @stsci-hack knows the secret sauce.

**Comment by pllim** [comment]
@mcara thanks for checking. Maybe I should open an issue over at `drizzlepac` about the logging level aspect.

**Comment by tddesjardins** [comment]
From discussions with @pllim and @jamienoss , my thinking now is that this behavior is due to the interaction between `subprocess.check_call()` and `jupyter`. I think this because the output from the `acstools` wrapper is sent to the terminal running the `jupyter` server, while directly calling the C executable inside the notebook directs STDOUT to the notebook's output cell. I'll need to test it more to confirm if that's the case, but in the meantime @pllim 's suggestion to directly call on the C executable works.

**Comment by pllim** [comment]
@tddesjardins , did you find out anything more about this? Any action is needed on the `acstools` side? If not, please close the issue.
