### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by nmiles2718** [spacetelescope/acstools#68]
Currently, the documentation for acstools contains no references to SINKCORR in the [calacs.e](https://acstools.readthedocs.io/en/stable/calacs_hstcal.html) section. In that same section, it also tells users that CALACS may be downloaded as part of the HSTCAL package in STSDAS. So we should update the docs to include links to astroconda and the SINKCORR step.

**Comment by pllim** [comment]
xref spacetelescope/hstcal#318

cc @stscicrawford and @SaOgaz

**Comment by nmiles2718** [comment]
In addition to adding documentation for SINKCORR, documentation should also be added here for the forward modeler. @jryon has developed a notebook that is a step-by-step guide to running the forward modeler, but we need additional docs setup in this repo so that the new interface shows up on the [acstools website](https://acstools.readthedocs.io/en/stable/).

**Comment by jryon** [comment]
Who's responsibility is it to update acstools documentation?

**Comment by pllim** [comment]
It is open source. Feel free to submit PRs!
