### ISSUE TITLE
MNT: Need a co-maintainer for code review etc

### ISSUE THREAD

**Issue by pllim** [spacetelescope/acstools#80]
Before I can enable "require PR review before merge" feature, I need someone to co-maintain this package and able to effectively review the PRs. cc @nden and @stscicrawford

**Comment by stscicrawford** [comment]
@mdlpstsci should be your back up on the DMD side.  We should also have a member from ACS to be a co-maintainer

**Comment by pllim** [comment]
@nmiles2718 volunteered and is approved by @nagrogin.
